// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module

	public static boolean entity_HasChildren(IContext context, myfirstmodule.proxies.TestEntity _testEntity)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("TestEntity", _testEntity == null ? null : _testEntity.getMendixObject());
			return (Boolean)Core.execute(context, "MyFirstModule.Entity_HasChildren", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}